VendingMachine/Controllers/ImageController.cs
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using VendingMachine.Service;

namespace VendingMachine.Controllers
{
    public class ImageController : Controller
    {
        private readonly IPictureService _service;

        public ImageController(IPictureService pictureService)
        {
            _service = pictureService;
        }

        [HttpGet]
        public async Task<ActionResult> Show(int? id)
        {
            if (id != null)
            {
                var pictureItem = await _service.Get((int)id);
                var fileContent = pictureItem.BinaryData;
                var fileName = $"{Path.GetFileNameWithoutExtension(Path.GetRandomFileName())}.jpg";
                return File(fileContent, "image/jpg", fileName);
            }
            return null;
        }
    }
}

VendingMachine/Controllers/VendingMachineController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using VendingMachine.BuisnesLogic;
using VendingMachine.Model;
using VendingMachine.Service;

namespace VendingMachine.Controllers
{
    public sealed class VendingMachineController : Controller
    {
        private readonly IStoreService _storeService;
        private readonly ICashBoxService _cashBoxService;
        private readonly IPurchaseManager _purchaseManager;
        private readonly IChangeSlot _changeSlot;
        private readonly IBasketSlot _basketSlot;

        public VendingMachineController(
             IStoreService storeService,
             ICashBoxService cashBoxService,
             IPurchaseManager purchaseManager,
             IChangeSlot changeSlot,
             IBasketSlot basketSlot)
        {
            _storeService = storeService;
            _cashBoxService = cashBoxService;
            _purchaseManager = purchaseManager;
            _changeSlot = changeSlot;
            _basketSlot = basketSlot;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetBalance()
        {
            var currentBalance = _purchaseManager.GetBalance();
            return Json(new { balance = currentBalance }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> GetStore()
        {
            var store = await _storeService.GetList();
            return Json(new { store = store }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> GetCoinSlots()
        {
            var cashBox = await _cashBoxService.GetList();
            return Json(new { cashBox = cashBox }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> TakeChange()
        {
            var change = await _purchaseManager.GetChange();
            _changeSlot.Change.AddRange(change);
            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult ClearChange()
        {
            _changeSlot.Clear();
            return Json(new { success = true });
        }

        public ActionResult GetChangeCoins()
        {
            return Json(new { change = _changeSlot }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> InsetCoin(Coin coin)
        {
            await _purchaseManager.InsertCoin(coin);
            return Json(new { success = true });
        }

        [HttpPost]
        public async Task<ActionResult> Buy(int id)
        {
            var drink =  await _purchaseManager.Buy(id);
            _basketSlot.Basket.Add(drink);
            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult ClearBasket()
        {
            _basketSlot.Clear();
            return Json(new { success = true });
        }

        public ActionResult GetBasket()
        {
            return Json(new { basket = _basketSlot }, JsonRequestBehavior.AllowGet);
        }

    }
}

VendingMachine/Views/VendingMachine/BasketSlot.cshtml
<div class="panel-group" ng-show="basket.IsBasketNotEmpty">
    <div class="panel panel-default">
        <div class="panel-heading">Ваша покупка:</div>
        <div class="panel-body">
            <div class="row">
                <div ng-repeat="basketItem in basket.Basket">
                    <div class="column">
                        <div class="card mb-4 shadow-sm">
                            <div class="card mb-4 shadow-sm">
                                <div class="panel panel-default">
                                    <div class="panel-heading"><strong>{{basketItem.Name}}</strong></div>
                                    <div class="panel-body">
                                        <p><img width="150" height="200" src='@Url.Action("show", "Image")?id={{basketItem.PictureId}}' /></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <a class="btn btn-lg btn-block btn-success" ng-click="clearBasket()">
                Забрать покупки
                <span class="glyphicon glyphicon-hand-right" width="30" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</div>

VendingMachine/Views/VendingMachine/ChangeSlot.cshtml
<div class="panel-group" ng-show="change.IsChangeExist">
    <div class="panel panel-default">
        <div class="panel-heading">Ваша сдача:</div>
        <div class="panel-body">
            <div class="row">
                <div ng-repeat="changeItem in change.Change">
                    <div class="col-xs-1-10">
                        <img width="40" height="40" src='@Url.Action("Show", "Image")?id={{changeItem.PictureId}}' />
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <a class="btn btn-lg btn-block btn-success" ng-click="clearChange()">
                Забрать сдачу
                <span class="glyphicon glyphicon-hand-right" width="30" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</div>

VendingMachine/Views/VendingMachine/CoinAcceptor.cshtml
<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">Монетоприёмник</div>
        <div class="panel-body">
            <p>Баланс:</p>
            <p class="customfont">{{ balance.TextValue }}</p>

            <p>Внести монты:</p>

            <div class="row">
                <div ng-repeat="cashBoxSlot in cashBox">
                    <div class="column">
                        <div class="card mb-5 shadow-sm">

                            <button class="btn btn-block btn-default" ng-click="insetCoin(cashBoxSlot.CoinSlotType)" ng-show="cashBoxSlot.IsEnable">
                                <img width="40" height="40" src='@Url.Action("show", "Image")?id={{cashBoxSlot.CoinSlotType.PictureId}}' />
                                {{cashBoxSlot.CoinSlotType.Name}}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <p>Выдать сдачу:</p>
            <button class="btn btn-lg btn-block btn-info" ng-click="takeChange()">
                <span class="glyphicon glyphicon glyphicon-ruble" width="30" aria-hidden="true"></span>
                Сдача
            </button>

        </div>
    </div>
</div>

VendingMachine/Views/VendingMachine/Index.cshtml
@{
    ViewBag.Title = "Автомат по продаже напитков";
}

<h2>@ViewBag.Title.</h2>


<div ng-app="VendingMachineModule">
    <div ng-controller="VendingMachineController">
        <div ng-init="updateBoard()"></div>

        <!-- Coin acceptor-->
        @Html.Partial("CoinAcceptor")

        <!-- Change slot-->
        @Html.Partial("ChangeSlot")

        <!-- Basket slot-->
        @Html.Partial("BasketSlot")

        <!--Shop window-->
        @Html.Partial("ShopWindow")
    </div>
</div>

VendingMachine/Views/VendingMachine/ShopWindow.cshtml
<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">Витрина</div>
        <div class="panel-body">
            <div class="container-fluid">
                <div class="row">
                    <div ng-repeat="productItem in store">
                        <div class="column" ng-show="productItem.Quantity > 0">
                            <div class="card mb-4 shadow-sm">

                                <div class="panel panel-default">
                                    <div class="panel-heading"><strong>{{productItem.Drink.Name}}</strong></div>
                                    <div class="panel-body">
                                        <p>Количество: {{productItem.Quantity}} штук</p>
                                        <p><img width="150" height="200" src='@Url.Action("show", "Image")?id={{productItem.Drink.PictureId}}' /></p>
                                    </div>
                                    <div class="panel-footer">
                                        <button type="button" class="btn btn-lg btn-block btn-success" ng-click="buy(productItem.Id)" ng-show="productItem.Drink.Price.Amount <= balance.Amount">Купить {{productItem.Product.Price.TextValue}}</button>
                                        <button type="button" class="btn btn-lg btn-block btn-danger" ng-show="productItem.Drink.Price.Amount > balance.Amount">{{productItem.Drink.Price.TextValue}}</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br><br><br><br>
        </div>
    </div>
</div>